FROM python:2.7.16-alpine3.9

# Install dependencies for Pillow, as well as install node and npm
RUN apk update && apk add build-base zlib-dev jpeg-dev freetype-dev nodejs nodejs-npm git

# Pillow is needed to generate the image in python
RUN pip install Pillow pycodestyle autopep8 enum34 coverage

# Pixelmatch is just a test-time dependency
RUN npm config set unsafe-perm true
RUN npm install --global https://github.com/mapbox/pixelmatch

CMD ["/bin/bash"]
